### ISSUE TITLE
" Error: could not find function "dataTableProxy" "

### ISSUE THREAD

**Issue by poshea-usgs** [USGS-R/WREG#127]
While using the web version of WREG and importing 'MatLab WREG project' I receive the following error when performing Site selection under 'Filter and select sites'.

Error: could not find function "dataTableProxy"

![image](https://user-images.githubusercontent.com/29262540/26899581-275569e6-4b95-11e7-8e06-cfca69c6339c.png)

**Comment by tjmills** [comment]
dataTableProxy is in the DT package. I would guess this error is occuring because you have an old version of the DT package, but I can't be sure.

I have updated the description file to require more recent versions of packages

**Comment by deladd-usgs** [comment]
I experienced the same error trying to import PeakFQ outputs. I just updated to the newest version of R (currently 3.4.1) and installed all available updates to packages. Even though I received the error, I was still able to complete the regression.
