### ISSUE TITLE
WREGgui() doesn't work

### ISSUE THREAD

**Issue by rwdudley-usgs** [USGS-R/WREG#131]
I get a blank open tab in the browser with the warning: `Error in : $ operator is invalid for atomic vectors`

```
> library(WREG)
> WREGgui()

Listening on http://127.0.0.1:3560
Warning: Error in : $ operator is invalid for atomic vectors
  63: tag
  62: tags$a
  59: FUN
  58: lapply
  57: buildTabset
  56: navbarPage
Warning: Error in : $ operator is invalid for atomic vectors
  63: tag
  62: tags$a
  59: FUN
  58: lapply
  57: buildTabset
  56: navbarPage
```

**Comment by jhammondusgs** [comment]
I have the same problem.

In browser tab I get this warning: ERROR: $ operator is invalid for atomic vectors

and in R studio: 
![image](https://user-images.githubusercontent.com/48726137/54618638-bb735580-4a39-11e9-98ef-b0f648604ba0.png)

**Comment by aspaetzel** [comment]
I am having the same issue.

> WREGgui()
Loading required package: shiny

Attaching package: ‘DT’

The following objects are masked from ‘package:shiny’:

    dataTableOutput, renderDataTable


Listening on http://127.0.0.1:7385
Warning: Error in : $ operator is invalid for atomic vectors
  63: tag
  62: tags$a
  59: FUN
  58: lapply
  57: buildTabset
  56: navbarPage
Warning: Error in : $ operator is invalid for atomic vectors
  63: tag
  62: tags$a
  59: FUN
  58: lapply
  57: buildTabset
  56: navbarPage

**Comment by wfarmer-usgs** [comment]
Try running these commands before opening the GUI:
install.packages("https://cran.r-project.org/src/contrib/Archive/shiny/shiny_1.0.3.tar.gz", repos = NULL, type = "source")
install.packages("knitr", repos = c("http://cran.us.r-project.org"))
install.packages("rmarkdown", repos = c("http://cran.us.r-project.org"))

The problem may stem from an update to the SHINY package.

**Comment by wfarmer-usgs** [comment]
I realize the previous message comes a year late. The WMA does not currently provide any support for this package. Better to contact the developer directly.

**Comment by jhammondusgs** [comment]
Thanks Will, when installing 1.0.3 Shiny and running, I get the error "must use at least Shiny 1.1", then when using Shiny 1.1.0, I get the old error "Warning: Error in $: $ operator is invalid for atomic vectors." No need to resolve, I'm using the line by line version, but just wanted to give you an update
