### ISSUE TITLE
Print function not formattign output of WREG classes

### ISSUE THREAD

**Issue by tjmills** [USGS-R/WREG#34]

**Comment by tjmills** [comment]
I think this is because its not a proper class definition. It should still work because its an exported funciton, however I Think the roxygen maybe is not exporting all three functions in the print script, just the first one.

Function works when defined in the global environment

**Comment by wfarmer-usgs** [comment]
How do we make it export all functions?  Add an additional export command in roxygen?

**Comment by wfarmer-usgs** [comment]
http://stackoverflow.com/questions/15932585/roxygen-two-functions-in-one-rd-file

That seems to be our solution.
