### ISSUE TITLE
WREG... fails

### ISSUE THREAD

**Issue by tjmills** [USGS-R/WREG#45]
Running WREG.GLS, WREG.WLS, or WREG.OLS fails with the new larger M. Kohn data.

**Comment by wfarmer-usgs** [comment]
How so?  Any more information?

Are the inputs bad or is the function bad?  I've tried it with massive datasets and never had a problem, so I'd be surprised if it was the function.  Does WREG.MLR work?

**Comment by tjmills** [comment]
If I had to guess its because the inputs are bad, but this is where you with better knowledge of the package is needed.

**Comment by tjmills** [comment]
Here is the error:

Warning: Error in <-: replacement has length zero
Stack trace (innermost first):
    68: Omega.GLS [C:/Users/tmills/Documents/USGS-R/WREG/R/Omega.GLS.R#263]
    67: WREG.GLS [C:/Users/tmills/Documents/USGS-R/WREG/R/WREG.GLS.R#150]
    66: eval [C:\Users\tmills\Documents\USGS-R\WREG\inst\Shiny/server.R#368]
    65: eval
    64: withProgress
    63: observeEventHandler [C:\Users\tmills\Documents\USGS-R\WREG\inst\Shiny/server.R#349]
     1: shiny::runApp

**Comment by tjmills** [comment]
Ah, maybe I see it. Log transform of Y variable caused some -Inf values, which appear to be the issue. A warning in the GUI during variable transform is needed. This fixes the issue with WREG.OLS but WREG.GLS still fails

**Comment by tjmills** [comment]
I emailed an example data input and script for reference

**Comment by tjmills** [comment]
Ha, also I just realized the WREG... sounds kind of snarky. What I meant by that is that the family of WREG functions fail

**Comment by wfarmer-usgs** [comment]
Joe, is this one resolved?

**Comment by tjmills** [comment]
Sort of, I believe it was failing because of the -Inf values resulting from the log transform. We can close it for now and maybe just reference it in issue #54

**Comment by wfarmer-usgs** [comment]
Great.  Thanks.
