### ISSUE TITLE
Improved error handling

### ISSUE THREAD

**Issue by wfarmer-usgs** [USGS-R/WREG#54]
Add graceful exits.

For main functions (WREG.*), address obvious input areas (non-allowed values: missing, infinite).

Descriptive error messages.

**Comment by wfarmer-usgs** [comment]
This is addressed in pull request #57.  However, that only addresses functions used in the GUI.  Should probably consider functions outside of the GUI but remaining in the package.

**Comment by tjmills** [comment]
Yes, similar error checking should be done throughout the package so lets leave this issue open for now as a reminder
